exception DivByZero;
def main() {
    try {
        print(1);
    }
}
