exception DivByZero;
exception OutOfBounds;
def foo() : int raises DivByZero, OutOfBounds, DivByZero {
    return 0;
}
def main() {
    print(1);
}
